name: GitHub Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: installing python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Installing Ansible
        run: |
          sudo apt update
          sudo apt install ansible -y

      - name: Saving the ssh key
        run: |
          echo ${{secrets.SSH_KEY}} >> kali
          chmod  600 kali
      
      - name : Running the ansible
        run : |
          ansible-playbook -i hosts.ini docker.yml 